### ISSUE TITLE
无法编译成功

### ISSUE THREAD

**Issue by ldeng76** [rrsunhome/excelsql-project#1]
重现步骤：
1. clone 
2. 在主目录下执行：mvn clean compile
3. 报以下错误： V:\tmp\excelsql\excelsql-generate\src\main\java\com\github\rrsunhome\excelsql\DefaultSqlGenerator.java:[10,43] 错误: 找不到符号:   类 FileParserFactory  等一共2个错误

**Comment by rrsunhome** [comment]
问题已修复，感谢你提出问题。
