### ISSUE TITLE
无法从 https://mvnrepository.com/ 仓库中找到并下载

### ISSUE THREAD

**Issue by ldeng76** [rrsunhome/excelsql-project#2]
在pom.xml中使用 以下语句无法下载 jar 包：

<dependency>
	<groupId>com.github.rrsunhome</groupId>
	<artifactId>excelsql-generate</artifactId>
	<version>2.1.0</version>
</dependency>

楼主，你这是发布在哪个仓库？

**Comment by rrsunhome** [comment]
Jar 包已推送到 Maven 中央仓库，请在相关仓库按 ‘rrsunhome’ 关键词查询，即可获取。

**Comment by rrsunhome** [comment]
Maven 最新版本集成依赖
<dependency>
  <groupId>com.github.rrsunhome</groupId>
  <artifactId>excelsql-generate</artifactId>
  <version>2.1.1</version>
</dependency>
